#!/usr/bin/env bash
# Unified web console for inference-gated mobile ALOHA data collection,
# processing/QC, and data/robot replay.
#
# Usage:
#   bash scripts/collection/collect_mobile_pipeline_web_inference.sh [dataset_dir] [start_episode_index] [left_target] [right_target]
#   bash scripts/collection/collect_mobile_pipeline_web_inference.sh [start_episode_index]
#
# Open:
#   http://<robot-ip>:8848/
#
# The original collection controller is left unchanged and is started behind
# this gateway. Run collect_mobile_pipeline_qc_web_four_camera.sh for the
# standalone four-camera QC page on port 8001.
set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/collection_ros_env.sh"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
COLLECTION_SCRIPT="${COLLECTION_SCRIPT:-${SCRIPT_DIR}/collect_mobile_episode_web.sh}"
PIPELINE_ROOT="${PIPELINE_ROOT:-${REPO_ROOT}/scripts/embodied_data_pipeline-main}"
PIPELINE_APP="${PIPELINE_APP:-${PIPELINE_ROOT}/scripts/pipeline_web_app.py}"
VISUALIZER_SCRIPT="${VISUALIZER_SCRIPT:-${REPO_ROOT}/scripts/replay/visualize_dataset_web.py}"

usage() {
    cat <<EOF
Usage:
  $0 [dataset_dir] [start_episode_index] [left_target] [right_target]
  $0 [dataset_dir] [left_target]
  $0 [start_episode_index]

Examples:
  $0 /home/agilex/data/market_6 0 "Apple"
  $0 /home/agilex/data/market_6 0 "Apple" "Milk"
  $0 /home/agilex/data/market_6 "Apple"
  $0 3

Environment defaults:
  DATA_DIR=<required unless dataset_dir argument is provided>
  TARGET_BOTTLE_A=<left_target argument or "target object">
  TARGET_BOTTLE_B=<right_target argument; empty means single-hand>
  COLLECTION_ARM_MODE=auto       auto: right_target present -> dual, otherwise single
  STAGE_PRESET_INFO_JSON=<auto-generated from target names unless provided>
  WEB_HOST=192.168.3.101
  WEB_PORT=8848
  COLLECTION_ENABLE=1
  COLLECTION_STAGED_CAPTURE_DEFAULT=0
  COLLECTION_AUTO_GRADE=A       every saved inference episode is graded A automatically
  RAW_MCAP_ONLY=1
  RUN_CONVERT=0
  RUN_QC=0
  FAILURE_ANNOTATIONS_JSON=\$DATA_DIR/manual_failure_annotations.json
                 legacy pipeline import path; new collection reviews write per-episode info json
  COLLECTION_WEB_PORT=auto
  PIPELINE_ENABLE=0
  PIPELINE_WEB_PORT=auto
  VISUALIZER_ENABLE=0
  VISUALIZER_WEB_PORT=auto
  VISUALIZER_HDF5_ROOT=\$DATA_DIR/aloha
  VISUALIZER_LEROBOT_ROOT=\$DATA_DIR/lerobot/<dataset_name>
  STATE_MACHINE_BRIDGE_ENABLE=1
  STATE_MACHINE_AUTO_ACTIVE_DEFAULT=1
  STATE_MACHINE_STAGED_DEFAULT=0
  INFERENCE_RECORD_TOPIC=/inference_record
  STATE_MACHINE_START_TOPIC=/state_machine/start
  STATE_MACHINE_END_TOPIC=/state_machine/end
  STATE_MACHINE_STAGE1_END_TOPIC=/state_machine/approaching_container/end
  STATE_MACHINE_STAGE2_END_TOPIC=/state_machine/grasping/end
  STATE_MACHINE_STAGE3_END_TOPIC=/state_machine/approaching_shopping_cart/end
  STATE_MACHINE_STAGE4_END_TOPIC=/state_maching/put_back/end
  STATE_MACHINE_STAGE4_END_TOPIC_ALIASES=/state_machine/put_back/end
  DATA_COLLECTION_START_TOPIC=/data_collection/start
  COLLECTION_SCENE_INVENTORY_JSON=${SCRIPT_DIR}/market_scene_inventory.json
                                    item inventory used to write per-episode scene info
  PIPELINE_DEFAULT_MCAP_PATH=<empty>
  PIPELINE_DATA_ROOT=<empty>
  PIPELINE_DEFAULT_ROBOT_TYPE=<empty>
  PIPELINE_DEFAULT_DATASET_NAME=<empty>
  PIPELINE_DEFAULT_TASK_TEXT=<empty>
  PIPELINE_DEFAULT_REPO_ID=<empty>
  PIPELINE_DEFAULT_CONVERT_JOBS=<empty>
  LEROBOT_PYTHON=/home/agilex/openpi/.venv/bin/python
  PIPELINE_DEFAULT_USE_DOCKER=0

Inference state-machine behavior:
  Recording starts only when both INFERENCE_RECORD_TOPIC=true and
  STATE_MACHINE_START_TOPIC=true have been observed by this independent bridge.
  Recording is saved when STATE_MACHINE_END_TOPIC=true.

Pages:
  /              unified four-module console
  /collection/   data collection controller
  /pipeline/     optional embedded MCAP conversion/QC page when PIPELINE_ENABLE=1
                 standalone four-camera QC page: collect_mobile_pipeline_qc_web_four_camera.sh on port 8001
  /visualize/    HDF5 and LeRobot browser visualizer
EOF
}

START_INDEX="${EPISODE_INDEX:-0}"
DATA_DIR_ARG=""
START_INDEX_ARG_SEEN=0
LEFT_TARGET_ARG=""
RIGHT_TARGET_ARG=""

while [ "$#" -gt 0 ]; do
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        -d|--data-dir)
            [ "$#" -ge 2 ] || {
                echo "[错误] $1 需要数据集目录参数" >&2
                exit 1
            }
            DATA_DIR_ARG="$2"
            shift 2
            ;;
        --left-target|--target-a|--bottle-a)
            [ "$#" -ge 2 ] || {
                echo "[错误] $1 需要左臂物品参数" >&2
                exit 1
            }
            LEFT_TARGET_ARG="$2"
            shift 2
            ;;
        --right-target|--target-b|--bottle-b)
            [ "$#" -ge 2 ] || {
                echo "[错误] $1 需要右臂物品参数" >&2
                exit 1
            }
            RIGHT_TARGET_ARG="$2"
            shift 2
            ;;
        -i|--start-index)
            [ "$#" -ge 2 ] || {
                echo "[错误] $1 需要 episode 起始编号" >&2
                exit 1
            }
            START_INDEX="$2"
            START_INDEX_ARG_SEEN=1
            shift 2
            ;;
        --data-dir=*)
            DATA_DIR_ARG="${1#*=}"
            shift
            ;;
        --left-target=*|--target-a=*|--bottle-a=*)
            LEFT_TARGET_ARG="${1#*=}"
            shift
            ;;
        --right-target=*|--target-b=*|--bottle-b=*)
            RIGHT_TARGET_ARG="${1#*=}"
            shift
            ;;
        --start-index=*)
            START_INDEX="${1#*=}"
            START_INDEX_ARG_SEEN=1
            shift
            ;;
        *)
            if [[ "$1" =~ ^[0-9]+$ ]] && { [ -z "${DATA_DIR_ARG}" ] || [ "${START_INDEX_ARG_SEEN}" -eq 0 ]; }; then
                START_INDEX="$1"
                START_INDEX_ARG_SEEN=1
            elif [ -z "${DATA_DIR_ARG}" ]; then
                DATA_DIR_ARG="$1"
            elif [ -z "${LEFT_TARGET_ARG}" ]; then
                LEFT_TARGET_ARG="$1"
            elif [ -z "${RIGHT_TARGET_ARG}" ]; then
                RIGHT_TARGET_ARG="$1"
            else
                echo "[错误] 无法识别参数: $1" >&2
                usage >&2
                exit 1
            fi
            shift
            ;;
    esac
done

[[ "${START_INDEX}" =~ ^[0-9]+$ ]] || {
    echo "[错误] 起始 episode index 必须是非负整数: ${START_INDEX}" >&2
    exit 1
}

if [ -n "${DATA_DIR_ARG}" ]; then
    DATA_DIR="${DATA_DIR_ARG}"
elif [ -n "${DATA_DIR:-}" ]; then
    DATA_DIR="${DATA_DIR}"
else
    echo "[错误] 必须指定数据集目录，例如:" >&2
    echo "  $0 /home/agilex/data/market_5" >&2
    echo "或设置 DATA_DIR=/home/agilex/data/market_5" >&2
    exit 1
fi

if [ -n "${LEFT_TARGET_ARG}" ]; then
    TARGET_BOTTLE_A="${LEFT_TARGET_ARG}"
elif [ -n "${TARGET_BOTTLE_A:-}" ]; then
    TARGET_BOTTLE_A="${TARGET_BOTTLE_A}"
elif [ -n "${BOTTLE_A:-}" ]; then
    TARGET_BOTTLE_A="${BOTTLE_A}"
else
    TARGET_BOTTLE_A="${LEFT_TARGET_DEFAULT:-target object}"
fi

if [ -n "${RIGHT_TARGET_ARG}" ]; then
    TARGET_BOTTLE_B="${RIGHT_TARGET_ARG}"
elif [ -n "${LEFT_TARGET_ARG}" ]; then
    TARGET_BOTTLE_B=""
elif [ -n "${TARGET_BOTTLE_B:-}" ]; then
    TARGET_BOTTLE_B="${TARGET_BOTTLE_B}"
elif [ -n "${BOTTLE_B:-}" ]; then
    TARGET_BOTTLE_B="${BOTTLE_B}"
else
    TARGET_BOTTLE_B=""
fi

COLLECTION_ARM_MODE="${COLLECTION_ARM_MODE:-auto}"
case "${COLLECTION_ARM_MODE}" in
    auto)
        if [ -n "${TARGET_BOTTLE_B}" ]; then
            COLLECTION_ARM_MODE="dual"
        else
            COLLECTION_ARM_MODE="single"
        fi
        ;;
    single|left|one)
        COLLECTION_ARM_MODE="single"
        TARGET_BOTTLE_B=""
        ;;
    dual|double|both|two)
        COLLECTION_ARM_MODE="dual"
        ;;
    *)
        echo "[错误] COLLECTION_ARM_MODE 只能是 auto/single/dual: ${COLLECTION_ARM_MODE}" >&2
        exit 1
        ;;
esac

if [ "${COLLECTION_ARM_MODE}" = "dual" ] && [ -z "${TARGET_BOTTLE_B}" ]; then
    echo "[错误] 双手模式需要指定右臂物品，例如: $0 ${DATA_DIR} ${START_INDEX} \"${TARGET_BOTTLE_A}\" \"Right target\"" >&2
    exit 1
fi

TARGET_BOTTLE_A_ZH="${TARGET_BOTTLE_A_ZH:-${BOTTLE_A_ZH:-${TARGET_BOTTLE_A}}}"
if [ "${COLLECTION_ARM_MODE}" = "single" ]; then
    TARGET_BOTTLE_B_ZH=""
else
    TARGET_BOTTLE_B_ZH="${TARGET_BOTTLE_B_ZH:-${BOTTLE_B_ZH:-${TARGET_BOTTLE_B}}}"
fi

WEB_HOST="${WEB_HOST:-192.168.3.101}"
WEB_PORT="${WEB_PORT:-8848}"
COLLECTION_ENABLE="${COLLECTION_ENABLE:-1}"
COLLECTION_STAGED_CAPTURE_DEFAULT="${COLLECTION_STAGED_CAPTURE_DEFAULT:-0}"
COLLECTION_AUTO_GRADE="${COLLECTION_AUTO_GRADE:-A}"
PIPELINE_ENABLE="${PIPELINE_ENABLE:-0}"
VISUALIZER_ENABLE="${VISUALIZER_ENABLE:-0}"
STATE_MACHINE_BRIDGE_ENABLE="${STATE_MACHINE_BRIDGE_ENABLE:-1}"
STATE_MACHINE_AUTO_ACTIVE_DEFAULT="${STATE_MACHINE_AUTO_ACTIVE_DEFAULT:-1}"
STATE_MACHINE_STAGED_DEFAULT="${STATE_MACHINE_STAGED_DEFAULT:-0}"
INFERENCE_RECORD_TOPIC="${INFERENCE_RECORD_TOPIC:-/inference_record}"
STATE_MACHINE_START_TOPIC="${STATE_MACHINE_START_TOPIC:-/state_machine/start}"
STATE_MACHINE_END_TOPIC="${STATE_MACHINE_END_TOPIC:-/state_machine/end}"
STATE_MACHINE_STAGE1_END_TOPIC="${STATE_MACHINE_STAGE1_END_TOPIC:-/state_machine/approaching_container/end}"
STATE_MACHINE_STAGE2_END_TOPIC="${STATE_MACHINE_STAGE2_END_TOPIC:-/state_machine/grasping/end}"
STATE_MACHINE_STAGE3_END_TOPIC="${STATE_MACHINE_STAGE3_END_TOPIC:-/state_machine/approaching_shopping_cart/end}"
STATE_MACHINE_STAGE4_END_TOPIC="${STATE_MACHINE_STAGE4_END_TOPIC:-/state_maching/put_back/end}"
STATE_MACHINE_STAGE4_END_TOPIC_ALIASES="${STATE_MACHINE_STAGE4_END_TOPIC_ALIASES:-/state_machine/put_back/end}"
DATA_COLLECTION_START_TOPIC="${DATA_COLLECTION_START_TOPIC:-/data_collection/start}"
LOG_ROOT="${WEB_LOG_ROOT:-${DATA_DIR%/}/logs/mobile_pipeline_web_inference}"
FAILURE_ANNOTATIONS_JSON="${FAILURE_ANNOTATIONS_JSON:-${DATA_DIR%/}/manual_failure_annotations.json}"
COLLECTION_SCENE_INVENTORY_JSON="${COLLECTION_SCENE_INVENTORY_JSON:-${SCRIPT_DIR}/market_scene_inventory.json}"
AUTO_STAGE_PRESET_PATH=0
if [ -z "${STAGE_PRESET_INFO_JSON:-}" ]; then
    STAGE_PRESET_INFO_JSON="${LOG_ROOT}/task_presets/${COLLECTION_ARM_MODE}_target_instructions.json"
    AUTO_STAGE_PRESET_PATH=1
fi
GENERATE_STAGE_PRESET_FROM_TARGETS="${GENERATE_STAGE_PRESET_FROM_TARGETS:-${AUTO_STAGE_PRESET_PATH}}"
STATE_MACHINE_CONTROL_FILE="${STATE_MACHINE_CONTROL_FILE:-${LOG_ROOT}/inference_state_machine_bridge_control.json}"
GATEWAY_LOG="${LOG_ROOT}/gateway_$(date +%Y%m%d_%H%M%S).log"
COLLECTION_LOG="${LOG_ROOT}/collection_$(date +%Y%m%d_%H%M%S).log"
PIPELINE_LOG="${LOG_ROOT}/pipeline_$(date +%Y%m%d_%H%M%S).log"
VISUALIZER_LOG="${LOG_ROOT}/visualizer_$(date +%Y%m%d_%H%M%S).log"
STATE_MACHINE_BRIDGE_LOG="${LOG_ROOT}/state_machine_bridge_$(date +%Y%m%d_%H%M%S).log"

COLLECTION_PID=""
PIPELINE_PID=""
VISUALIZER_PID=""
GATEWAY_PID=""
STATE_MACHINE_BRIDGE_PID=""
COLLECTION_URL=""
PIPELINE_URL=""
VISUALIZER_URL=""

is_truthy() {
    case "${1:-}" in
        1|true|TRUE|yes|YES|on|ON) return 0 ;;
        *) return 1 ;;
    esac
}

log() {
    printf '[%s] %s\n' "$(date '+%F %T')" "$*"
}

die() {
    echo "[错误] $*" >&2
    exit 1
}

write_target_stage_preset() {
    is_truthy "${GENERATE_STAGE_PRESET_FROM_TARGETS}" || return 0
    mkdir -p "$(dirname "${STAGE_PRESET_INFO_JSON}")"
    python3 - \
        "${STAGE_PRESET_INFO_JSON}" \
        "${COLLECTION_ARM_MODE}" \
        "${TARGET_BOTTLE_A}" \
        "${TARGET_BOTTLE_B}" <<'PY'
import json
import os
import sys

path = sys.argv[1]
mode = sys.argv[2]
left_target = sys.argv[3]
right_target = sys.argv[4]

if mode == "dual":
    stages = [
        "Move chassis to shelf.",
        f"Grasp {left_target} with the left hand, then grasp {right_target} with the right hand.",
        "Move chassis to cart.",
        f"Place {left_target} into the cart with the left hand, then place {right_target} into the cart with the right hand.",
        "Move chassis to start.",
    ]
else:
    stages = [
        "Move chassis to shelf.",
        f"Grasp {left_target} with the left hand.",
        "Move chassis to cart.",
        f"Place {left_target} into the cart with the left hand.",
        "Move chassis to start.",
    ]

payload = {
    "mark": {
        "full-instructions-en": ["\n".join(stages)],
        "full-instructions-zh": ["\n".join(stages)],
        "segment-instructions": [
            {
                "description_en": [text],
                "description_zh": [text],
            }
            for text in stages
        ],
    }
}

os.makedirs(os.path.dirname(path), exist_ok=True)
tmp = f"{path}.tmp"
with open(tmp, "w", encoding="utf-8") as handle:
    json.dump(payload, handle, ensure_ascii=False, indent=2)
    handle.write("\n")
os.replace(tmp, path)
PY
}

find_free_port() {
    python3 - "$1" <<'PY'
import socket
import sys

start = int(sys.argv[1])
for port in range(start, start + 200):
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            sock.bind(("127.0.0.1", port))
        except OSError:
            continue
        print(port)
        raise SystemExit(0)
raise SystemExit(f"no free port from {start}")
PY
}

wait_for_port() {
    local port="$1"
    local label="$2"
    local timeout="${3:-30}"
    local connect_host="${4:-127.0.0.1}"
    python3 - "$port" "$label" "$timeout" "$connect_host" <<'PY'
import socket
import sys
import time

port = int(sys.argv[1])
label = sys.argv[2]
timeout = float(sys.argv[3])
host = sys.argv[4]
deadline = time.time() + timeout
last_error = None
while time.time() < deadline:
    try:
        with socket.create_connection((host, port), timeout=0.5):
            raise SystemExit(0)
    except OSError as exc:
        last_error = exc
        time.sleep(0.2)
raise SystemExit(f"{label} did not open {host}:{port}: {last_error}")
PY
}

print_web_urls() {
    local display_host="${WEB_PUBLIC_HOST:-${WEB_HOST}}"
    local local_host="${WEB_HOST}"
    local route_ip=""
    local candidate_ips=""
    if [ "${WEB_HOST}" = "0.0.0.0" ] || [ "${WEB_HOST}" = "::" ]; then
        local_host="127.0.0.1"
        if [ -z "${WEB_PUBLIC_HOST:-}" ]; then
            route_ip="$(ip route get 1.1.1.1 2>/dev/null | awk '{for (i=1; i<=NF; i++) if ($i == "src") {print $(i+1); exit}}')"
            display_host="${route_ip:-127.0.0.1}"
        fi
        candidate_ips="$(hostname -I 2>/dev/null | tr ' ' '\n' | sed '/^$/d' | paste -sd ' ' -)"
    fi
    echo ""
    echo "===== 统一数据网站已启动 ====="
    echo "本机访问: http://${local_host}:${WEB_PORT}/"
    echo "外部访问: http://${display_host}:${WEB_PORT}/"
    if [ -n "${candidate_ips}" ]; then
        echo "本机 IP 候选: ${candidate_ips}"
    fi
    echo "采集模块日志: ${COLLECTION_LOG}"
    echo "处理模块日志: ${PIPELINE_LOG}"
    if is_truthy "${VISUALIZER_ENABLE}"; then
        echo "可视化模块日志: ${VISUALIZER_LOG}"
    fi
    if is_truthy "${STATE_MACHINE_BRIDGE_ENABLE}" && is_truthy "${COLLECTION_ENABLE}"; then
        echo "状态机桥接日志: ${STATE_MACHINE_BRIDGE_LOG}"
    fi
    echo "网关日志: ${GATEWAY_LOG}"
}

start_collection() {
    is_truthy "${COLLECTION_ENABLE}" || return 0
    [ -f "${COLLECTION_SCRIPT}" ] || die "找不到采集脚本: ${COLLECTION_SCRIPT}"
    local port
    port="${COLLECTION_WEB_PORT:-}"
    if [ -z "${port}" ] || [ "${port}" = "auto" ]; then
        port="$(find_free_port "$((WEB_PORT + 1))")"
    fi
    COLLECTION_WEB_PORT="${port}"
    COLLECTION_URL="http://127.0.0.1:${COLLECTION_WEB_PORT}"
    log "启动采集模块: ${COLLECTION_URL}"
    local cmd=(
        env
        WEB_HOST=127.0.0.1
        WEB_PORT="${COLLECTION_WEB_PORT}"
        DATA_DIR="${DATA_DIR}"
        EPISODE_INDEX="${START_INDEX}"
        STAGED_CAPTURE="${COLLECTION_STAGED_CAPTURE_DEFAULT}"
        STAGE_PRESET_INFO_JSON="${STAGE_PRESET_INFO_JSON}"
        TARGET_BOTTLE_A="${TARGET_BOTTLE_A}"
        TARGET_BOTTLE_B="${TARGET_BOTTLE_B}"
        TARGET_BOTTLE_A_ZH="${TARGET_BOTTLE_A_ZH}"
        TARGET_BOTTLE_B_ZH="${TARGET_BOTTLE_B_ZH}"
        COLLECTION_SCENE_INVENTORY_JSON="${COLLECTION_SCENE_INVENTORY_JSON}"
        COLLECTION_AUTO_GRADE="${COLLECTION_AUTO_GRADE}"
        RAW_MCAP_ONLY="${RAW_MCAP_ONLY:-1}"
        RUN_CONVERT="${RUN_CONVERT:-0}"
        RUN_QC="${RUN_QC:-0}"
        RUN_LEROBOT="0"
        BACKGROUND_PROCESSING="0"
        WEB_RUNTIME_DIR="${WEB_RUNTIME_DIR:-${LOG_ROOT}/inference_collector_runtime}"
        bash "${COLLECTION_SCRIPT}" "${START_INDEX}"
    )
    if command -v setsid >/dev/null 2>&1; then
        setsid "${cmd[@]}" >"${COLLECTION_LOG}" 2>&1 &
    else
        "${cmd[@]}" >"${COLLECTION_LOG}" 2>&1 &
    fi
    COLLECTION_PID="$!"
    if ! wait_for_port "${COLLECTION_WEB_PORT}" "collection web" 35; then
        tail -120 "${COLLECTION_LOG}" >&2 || true
        die "采集模块启动失败"
    fi
}

start_pipeline() {
    is_truthy "${PIPELINE_ENABLE}" || return 0
    [ -f "${PIPELINE_APP}" ] || die "找不到流水线网页: ${PIPELINE_APP}"
    local port
    port="${PIPELINE_WEB_PORT:-}"
    if [ -z "${port}" ] || [ "${port}" = "auto" ]; then
        port="$(find_free_port 8890)"
        if [ "${port}" = "${COLLECTION_WEB_PORT:-}" ]; then
            port="$(find_free_port "$((port + 1))")"
        fi
    fi
    PIPELINE_WEB_PORT="${port}"
    PIPELINE_URL="http://127.0.0.1:${PIPELINE_WEB_PORT}"
    local pipeline_data_root pipeline_lerobot_python
    pipeline_data_root="${PIPELINE_DATA_ROOT:-}"
    pipeline_lerobot_python="${LEROBOT_PYTHON:-}"
    if [ -z "${pipeline_lerobot_python}" ]; then
        if [ -x /home/agilex/openpi/.venv/bin/python ]; then
            pipeline_lerobot_python=/home/agilex/openpi/.venv/bin/python
        elif [ -x /home/agilex/miniforge3/envs/lerobot/bin/python ]; then
            pipeline_lerobot_python=/home/agilex/miniforge3/envs/lerobot/bin/python
        else
            pipeline_lerobot_python=python3
        fi
    fi
    log "启动数据处理/质检模块: ${PIPELINE_URL}"
    env \
        PIPELINE_DATA_ROOT="${pipeline_data_root}" \
        PIPELINE_DEFAULT_MCAP_PATH="${PIPELINE_DEFAULT_MCAP_PATH:-}" \
        PIPELINE_DEFAULT_DATASET_NAME="${PIPELINE_DEFAULT_DATASET_NAME:-}" \
        PIPELINE_DEFAULT_HDF5_ROOT="${PIPELINE_DEFAULT_HDF5_ROOT:-}" \
        PIPELINE_DEFAULT_QC_ROOT="${PIPELINE_DEFAULT_QC_ROOT:-}" \
        PIPELINE_DEFAULT_LEROBOT_ROOT="${PIPELINE_DEFAULT_LEROBOT_ROOT:-}" \
        PIPELINE_DEFAULT_ROBOT_TYPE="${PIPELINE_DEFAULT_ROBOT_TYPE:-}" \
        PIPELINE_DEFAULT_TASK_TEXT="${PIPELINE_DEFAULT_TASK_TEXT:-}" \
        PIPELINE_DEFAULT_REPO_ID="${PIPELINE_DEFAULT_REPO_ID:-}" \
        PIPELINE_DEFAULT_CONVERT_JOBS="${PIPELINE_DEFAULT_CONVERT_JOBS:-}" \
        PIPELINE_DEFAULT_USE_DOCKER="${PIPELINE_DEFAULT_USE_DOCKER:-0}" \
        PIPELINE_FAILURE_ANNOTATIONS_JSON="${FAILURE_ANNOTATIONS_JSON}" \
        LEROBOT_PYTHON="${pipeline_lerobot_python}" \
        python3 -u "${PIPELINE_APP}" --host 127.0.0.1 --port "${PIPELINE_WEB_PORT}" >"${PIPELINE_LOG}" 2>&1 &
    PIPELINE_PID="$!"
    if ! wait_for_port "${PIPELINE_WEB_PORT}" "pipeline web" 20; then
        tail -120 "${PIPELINE_LOG}" >&2 || true
        die "数据处理/质检模块启动失败"
    fi
}

start_visualizer() {
    is_truthy "${VISUALIZER_ENABLE}" || return 0
    [ -f "${VISUALIZER_SCRIPT}" ] || die "找不到数据可视化脚本: ${VISUALIZER_SCRIPT}"
    local port
    port="${VISUALIZER_WEB_PORT:-}"
    if [ -z "${port}" ] || [ "${port}" = "auto" ]; then
        port="$(find_free_port 8765)"
        if [ "${port}" = "${COLLECTION_WEB_PORT:-}" ] || [ "${port}" = "${PIPELINE_WEB_PORT:-}" ]; then
            port="$(find_free_port "$((port + 1))")"
        fi
    fi
    VISUALIZER_WEB_PORT="${port}"
    VISUALIZER_URL="http://127.0.0.1:${VISUALIZER_WEB_PORT}"

    local dataset_name
    dataset_name="$(basename "${DATA_DIR%/}")"
    local hdf5_root="${VISUALIZER_HDF5_ROOT:-${DATA_DIR%/}/aloha}"
    local lerobot_root="${VISUALIZER_LEROBOT_ROOT:-${DATA_DIR%/}/lerobot/${dataset_name}}"
    if [ ! -d "${lerobot_root}" ] && [ -d "${DATA_DIR%/}/lerobot" ]; then
        lerobot_root="${DATA_DIR%/}/lerobot"
    fi

    log "启动数据可视化模块: ${VISUALIZER_URL}"
    python3 -u "${VISUALIZER_SCRIPT}" \
        --host 127.0.0.1 \
        --port "${VISUALIZER_WEB_PORT}" \
        --data-dir "${DATA_DIR}" \
        --hdf5-root "${hdf5_root}" \
        --lerobot-root "${lerobot_root}" \
        --start-episode "${START_INDEX}" \
        >"${VISUALIZER_LOG}" 2>&1 &
    VISUALIZER_PID="$!"
    if ! wait_for_port "${VISUALIZER_WEB_PORT}" "dataset visualizer web" 25; then
        tail -120 "${VISUALIZER_LOG}" >&2 || true
        die "数据可视化模块启动失败"
    fi
}

terminate_process() {
    local pid="$1"
    local signal="$2"
    if [ -z "${pid}" ] || ! kill -0 "${pid}" >/dev/null 2>&1; then
        return 0
    fi
    kill "-${signal}" "-${pid}" >/dev/null 2>&1 || kill "-${signal}" "${pid}" >/dev/null 2>&1 || true
}

wait_process_exit() {
    local pid="$1"
    local tenths="${2:-30}"
    local waited=0
    while [ "${waited}" -lt "${tenths}" ]; do
        if ! kill -0 "${pid}" >/dev/null 2>&1; then
            wait "${pid}" 2>/dev/null || true
            return 0
        fi
        sleep 0.1
        waited=$((waited + 1))
    done
    return 1
}

stop_child() {
    local pid="$1"
    [ -n "${pid}" ] || return 0
    if ! kill -0 "${pid}" >/dev/null 2>&1; then
        wait "${pid}" 2>/dev/null || true
        return 0
    fi
    # Bash background jobs may inherit SIGINT=ignore. TERM is trapped by the
    # collection controller and handled by rclpy, and reliably stops Web jobs.
    terminate_process "${pid}" TERM
    wait_process_exit "${pid}" 200 && return 0
    terminate_process "${pid}" KILL
    wait "${pid}" 2>/dev/null || true
}

stop_port_listeners() {
    local port="$1"
    [ -n "${port:-}" ] || return 0
    local pid
    while IFS= read -r pid; do
        [ -n "${pid}" ] || continue
        stop_child "${pid}"
    done < <(lsof -ti TCP:"${port}" -sTCP:LISTEN 2>/dev/null || true)
}

start_gateway() {
    python3 -u - \
        "${WEB_HOST}" \
        "${WEB_PORT}" \
        "${COLLECTION_URL}" \
        "${PIPELINE_URL}" \
        "${VISUALIZER_URL}" \
        "${COLLECTION_ENABLE}" \
        "${PIPELINE_ENABLE}" \
        "${VISUALIZER_ENABLE}" \
        "${STATE_MACHINE_BRIDGE_ENABLE}" \
        "${STATE_MACHINE_CONTROL_FILE}" <<'PY' >"${GATEWAY_LOG}" 2>&1 &
from __future__ import annotations

import http.client
import json
import os
import sys
import threading
import time
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlparse

host = sys.argv[1]
port = int(sys.argv[2])
collection_url = sys.argv[3].rstrip("/")
pipeline_url = sys.argv[4].rstrip("/")
visualizer_url = sys.argv[5].rstrip("/")
collection_enabled = sys.argv[6].lower() in {"1", "true", "yes", "on"}
pipeline_enabled = sys.argv[7].lower() in {"1", "true", "yes", "on"}
visualizer_enabled = sys.argv[8].lower() in {"1", "true", "yes", "on"}
automation_available = sys.argv[9].lower() in {"1", "true", "yes", "on"} and collection_enabled
automation_control_file = sys.argv[10]

COLLECTION_COMMANDS = {
    "/status",
    "/config",
    "/artifact",
    "/start",
    "/stage",
    "/stop",
    "/save",
    "/abandon",
    "/discard",
    "/check",
    "/estop",
    "/soft_stop",
    "/reset_arm",
    "/return_zero",
    "/quality/review",
    "/exit",
    "/quit",
    "/replay/visualize",
    "/replay/robot",
    "/replay/stop",
}

HOP_BY_HOP_HEADERS = {
    "connection",
    "keep-alive",
    "proxy-authenticate",
    "proxy-authorization",
    "te",
    "trailers",
    "transfer-encoding",
    "upgrade",
}


def module_unavailable(handler: BaseHTTPRequestHandler, name: str) -> None:
    body = json.dumps({"ok": False, "error": f"{name} module is disabled"}, ensure_ascii=False).encode("utf-8")
    handler.send_response(HTTPStatus.SERVICE_UNAVAILABLE)
    handler.send_header("Content-Type", "application/json; charset=utf-8")
    handler.send_header("Content-Length", str(len(body)))
    handler.send_header("Cache-Control", "no-store")
    handler.end_headers()
    handler.wfile.write(body)


def atomic_write_json(path: str, payload: dict) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = f"{path}.tmp"
    with open(tmp, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False)
    os.replace(tmp, path)


def read_automation_state() -> dict:
    if not automation_available:
        return {"available": False, "enabled": False, "message": "自动监听不可用"}
    try:
        with open(automation_control_file, "r", encoding="utf-8") as handle:
            data = json.load(handle)
    except (FileNotFoundError, json.JSONDecodeError):
        data = {}
    enabled = bool(data.get("enabled", False))
    staged_enabled = bool(data.get("staged_enabled", False))
    return {
        "available": True,
        "enabled": enabled,
        "staged_enabled": staged_enabled,
        "updated_at": data.get("updated_at", ""),
        "phase": data.get("phase", "idle" if enabled else "disabled"),
        "message": data.get("message") or (
            "自动监听已启用；未开始录制，等待状态机 start 开启本条采集" if enabled else "自动监听未启用"
        ),
        "inference_record_topic": data.get("inference_record_topic", ""),
        "inference_record_active": bool(data.get("inference_record_active", False)),
        "state_machine_start_active": bool(data.get("state_machine_start_active", False)),
        "start_topic": data.get("start_topic", ""),
        "end_topic": data.get("end_topic", ""),
        "stage_topics": data.get("stage_topics", []),
        "active_stage": data.get("active_stage", 0),
        "completed_stages": data.get("completed_stages", 0),
        "stage_count": data.get("stage_count", 5),
        "ready_topic": data.get("ready_topic", ""),
        "collection_url": data.get("collection_url", ""),
        "last_event": data.get("last_event", ""),
        "last_error": data.get("last_error", ""),
    }


def set_automation_state(enabled: bool) -> dict:
    if not automation_available:
        return read_automation_state()
    try:
        with open(automation_control_file, "r", encoding="utf-8") as handle:
            payload = json.load(handle)
    except (FileNotFoundError, json.JSONDecodeError):
        payload = {}
    payload.update({
        "enabled": bool(enabled),
        "phase": "idle" if enabled else "disabled",
        "message": (
            (
                "自动监听已启用；分阶段模式已选择，等待状态机 start 开启第一阶段"
                if bool(payload.get("staged_enabled", False))
                else "自动监听已启用；未开始录制，等待状态机 start 开启本条采集"
            )
            if enabled
            else "自动监听已关闭；手动采集按钮仍可正常使用"
        ),
        "last_error": "",
        "updated_at": time.strftime("%F %T"),
    })
    atomic_write_json(automation_control_file, payload)
    return read_automation_state()


def set_staged_automation_state(staged_enabled: bool) -> dict:
    if not automation_available:
        return read_automation_state()
    try:
        with open(automation_control_file, "r", encoding="utf-8") as handle:
            payload = json.load(handle)
    except (FileNotFoundError, json.JSONDecodeError):
        payload = {}
    enabled = bool(payload.get("enabled", False))
    payload.update({
        "staged_enabled": bool(staged_enabled),
        "phase": payload.get("phase", "idle" if enabled else "disabled"),
        "message": (
            "已选择分阶段自动采集；下一次 start 将按五阶段逻辑采集。"
            if staged_enabled
            else "已选择不分阶段自动采集；下一次 start 将按原逻辑采集。"
        ),
        "last_error": "",
        "updated_at": time.strftime("%F %T"),
    })
    atomic_write_json(automation_control_file, payload)
    return read_automation_state()


def read_json_body(handler: BaseHTTPRequestHandler) -> dict:
    length = int(handler.headers.get("Content-Length") or 0)
    if length <= 0:
        return {}
    body = handler.rfile.read(min(length, 65536)).decode("utf-8")
    if not body.strip():
        return {}
    return json.loads(body)


def copy_request_headers(handler: BaseHTTPRequestHandler) -> dict[str, str]:
    headers: dict[str, str] = {}
    for key, value in handler.headers.items():
        lower = key.lower()
        if lower in HOP_BY_HOP_HEADERS or lower == "host":
            continue
        headers[key] = value
    return headers


def proxy(handler: BaseHTTPRequestHandler, base_url: str, target_path: str, send_body: bool = True) -> None:
    parsed_base = urlparse(base_url)
    body = b""
    if handler.command in {"POST", "PUT", "PATCH"}:
        length = int(handler.headers.get("Content-Length") or 0)
        body = handler.rfile.read(length) if length > 0 else b""
    headers = copy_request_headers(handler)
    if body and "Content-Length" not in headers:
        headers["Content-Length"] = str(len(body))
    conn = http.client.HTTPConnection(parsed_base.hostname, parsed_base.port, timeout=300)
    try:
        conn.request(handler.command, target_path, body=body, headers=headers)
        resp = conn.getresponse()
        handler.send_response(resp.status, resp.reason)
        for key, value in resp.getheaders():
            if key.lower() in HOP_BY_HOP_HEADERS:
                continue
            handler.send_header(key, value)
        handler.send_header("X-Unified-Gateway", "1")
        handler.end_headers()
        if send_body and handler.command != "HEAD":
            while True:
                chunk = resp.read(64 * 1024)
                if not chunk:
                    break
                handler.wfile.write(chunk)
    except Exception as exc:
        payload = json.dumps({"ok": False, "error": str(exc)}, ensure_ascii=False).encode("utf-8")
        handler.send_response(HTTPStatus.BAD_GATEWAY)
        handler.send_header("Content-Type", "application/json; charset=utf-8")
        handler.send_header("Content-Length", str(len(payload)))
        handler.end_headers()
        handler.wfile.write(payload)
    finally:
        conn.close()


def strip_prefix(path: str, prefix: str) -> str:
    if path == prefix.rstrip("/"):
        return "/"
    stripped = path[len(prefix.rstrip("/")) :]
    return stripped or "/"


def with_query(path: str, query: str) -> str:
    return path + (("?" + query) if query else "")


def route_backend(parsed) -> tuple[str, str] | tuple[None, None]:
    path = parsed.path.rstrip("/") or "/"
    raw_path = parsed.path or "/"
    if raw_path.startswith("/collection/") or path == "/collection":
        return "collection", strip_prefix(raw_path, "/collection")
    if raw_path.startswith("/pipeline/") or path == "/pipeline":
        return "pipeline", strip_prefix(raw_path, "/pipeline")
    if raw_path.startswith("/visualize/") or path == "/visualize":
        return "visualizer", strip_prefix(raw_path, "/visualize")
    if path in COLLECTION_COMMANDS:
        return "collection", raw_path
    if (
        path == "/api"
        or raw_path.startswith("/api/")
        or path == "/replay"
        or raw_path.startswith("/replay/")
        or path == "/video"
        or raw_path.startswith("/video/")
        or path == "/lerobot-replay"
        or raw_path.startswith("/lerobot-replay/")
        or path == "/lerobot-video"
        or raw_path.startswith("/lerobot-video/")
    ):
        return "pipeline", raw_path
    return None, None


def page() -> str:
    collection_src = "/collection/" if collection_enabled else "about:blank"
    robot_replay_src = "/collection/?view=robot_replay" if collection_enabled else "about:blank"
    pipeline_src = "/pipeline/" if pipeline_enabled else "about:blank"
    visualizer_src = "/visualize/" if visualizer_enabled else "about:blank"
    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>松灵 ALOHA 数据工作台</title>
  <style>
    :root {{
      font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      background: #eef2f6;
      color: #17202a;
    }}
    body {{
      margin: 0;
      min-height: 100vh;
      background: #eef2f6;
    }}
    header {{
      display: grid;
      grid-template-columns: 1fr auto auto;
      gap: 16px;
      align-items: center;
      padding: 14px 18px;
      border-bottom: 1px solid #cfd8e3;
      background: #ffffff;
      position: sticky;
      top: 0;
      z-index: 10;
    }}
    h1 {{
      margin: 0;
      font-size: 20px;
      line-height: 1.25;
      letter-spacing: 0;
    }}
    nav {{
      display: grid;
      grid-template-columns: repeat(4, minmax(110px, 1fr));
      gap: 8px;
    }}
    button {{
      min-height: 40px;
      border: 1px solid #b8c2d0;
      border-radius: 6px;
      padding: 0 12px;
      background: #ffffff;
      color: #263445;
      font-size: 14px;
      font-weight: 700;
      cursor: pointer;
    }}
    button.active {{
      background: #14532d;
      border-color: #14532d;
      color: #ffffff;
    }}
    .automation {{
      display: grid;
      grid-template-columns: auto auto auto;
      gap: 8px;
      align-items: center;
      justify-content: end;
      min-width: 360px;
    }}
    .automation button {{
      background: #0f766e;
      border-color: #0f766e;
      color: #ffffff;
    }}
    .automation button.stop {{
      background: #b42318;
      border-color: #b42318;
    }}
    .automation button:disabled {{
      background: #e5e7eb;
      border-color: #cbd5e1;
      color: #64748b;
      cursor: not-allowed;
    }}
    .automation span {{
      font-size: 12px;
      font-weight: 700;
      color: #475569;
      white-space: nowrap;
    }}
    .automation-toggle {{
      display: inline-flex;
      align-items: center;
      gap: 6px;
      min-height: 40px;
      padding: 0 10px;
      border: 1px solid #b8c2d0;
      border-radius: 6px;
      background: #ffffff;
      color: #263445;
      font-size: 13px;
      font-weight: 750;
      white-space: nowrap;
    }}
    .automation-toggle input {{
      width: 16px;
      height: 16px;
      margin: 0;
    }}
    .automation-banner {{
      display: grid;
      grid-template-columns: auto 1fr auto;
      gap: 10px;
      align-items: center;
      min-height: 42px;
      padding: 8px 18px;
      border-bottom: 1px solid #cfd8e3;
      background: #ecfdf5;
      color: #12352b;
      font-size: 13px;
    }}
    .automation-banner.off {{
      background: #f8fafc;
      color: #475569;
    }}
    .automation-banner.error {{
      background: #fff1f2;
      color: #7f1d1d;
    }}
    .automation-badge {{
      display: inline-flex;
      align-items: center;
      min-height: 24px;
      padding: 0 9px;
      border-radius: 6px;
      background: #047857;
      color: #ffffff;
      font-size: 12px;
      font-weight: 800;
      white-space: nowrap;
    }}
    .automation-banner.off .automation-badge {{
      background: #64748b;
    }}
    .automation-banner.error .automation-badge {{
      background: #b42318;
    }}
    .automation-detail {{
      min-width: 0;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
      font-weight: 700;
    }}
    .automation-topics {{
      color: #475569;
      font-size: 12px;
      white-space: nowrap;
    }}
    main {{
      height: calc(100vh - 112px);
      min-height: 680px;
    }}
    .panel {{
      display: none;
      width: 100%;
      height: 100%;
    }}
    .panel.active {{
      display: block;
    }}
    iframe {{
      display: block;
      width: 100%;
      height: 100%;
      border: 0;
      background: #ffffff;
    }}
    .frame-wrap {{
      min-width: 0;
      min-height: 0;
      background: #ffffff;
    }}
    .frame-title {{
      display: flex;
      align-items: center;
      min-height: 34px;
      padding: 0 12px;
      border-bottom: 1px solid #d8dee8;
      font-size: 13px;
      font-weight: 750;
      color: #3d4a5c;
      background: #f8fafc;
    }}
    .frame-wrap iframe {{
      height: calc(100% - 35px);
    }}
    .empty {{
      padding: 24px;
      color: #52606d;
      font-size: 14px;
    }}
    @media (max-width: 980px) {{
      header {{
        grid-template-columns: 1fr;
        align-items: stretch;
      }}
      nav {{
        grid-template-columns: 1fr;
      }}
      .automation {{
        grid-template-columns: 1fr;
        justify-content: stretch;
      }}
      .automation-toggle {{
        justify-content: center;
      }}
      .automation span {{
        white-space: normal;
      }}
      .automation-banner {{
        grid-template-columns: 1fr;
        align-items: stretch;
      }}
      .automation-detail,
      .automation-topics {{
        white-space: normal;
      }}
      main {{
        height: auto;
      }}
      .panel {{
        height: calc(100vh - 184px);
        min-height: 720px;
      }}
    }}
  </style>
</head>
<body>
  <header>
    <h1>松灵 ALOHA 数据工作台</h1>
    <nav>
      <button id="tabCollect" class="active" type="button" data-panel="collect">数据采集</button>
      <button id="tabProcess" type="button" data-panel="process">质量检查与转换</button>
      <button id="tabVisualize" type="button" data-panel="visualize">数据可视化</button>
      <button id="tabRobotReplay" type="button" data-panel="robotReplay">真机回放</button>
    </nav>
    <div class="automation">
      <button id="autoCollect" type="button">启用自动监听</button>
      <label class="automation-toggle"><input id="stagedAutoCollect" type="checkbox"> 分阶段</label>
      <span id="autoCollectState">自动监听未启用</span>
    </div>
  </header>
  <div id="autoCollectBanner" class="automation-banner off">
    <span id="autoCollectBadge" class="automation-badge">AUTO</span>
    <span id="autoCollectDetail" class="automation-detail">自动监听状态加载中</span>
    <span id="autoCollectTopics" class="automation-topics"></span>
  </div>
  <main>
    <section id="panelCollect" class="panel active">
      {"<iframe src='" + collection_src + "' title='数据采集'></iframe>" if collection_enabled else "<div class='empty'>采集模块未启用。</div>"}
    </section>
    <section id="panelProcess" class="panel">
      {"<iframe src='" + pipeline_src + "' title='质量检查与转换'></iframe>" if pipeline_enabled else "<div class='empty'>质量检查与转换模块未启用。</div>"}
    </section>
    <section id="panelVisualize" class="panel">
      {"<iframe src='" + visualizer_src + "' title='数据可视化'></iframe>" if visualizer_enabled else "<div class='empty'>数据可视化模块未启用。</div>"}
    </section>
    <section id="panelRobotReplay" class="panel">
      {"<iframe src='" + robot_replay_src + "' title='真机回放与急停'></iframe>" if collection_enabled else "<div class='empty'>真机回放模块未启用。</div>"}
    </section>
  </main>
  <script>
    const buttons = Array.from(document.querySelectorAll("nav button"));
    const panels = {{
      collect: document.getElementById("panelCollect"),
      process: document.getElementById("panelProcess"),
      visualize: document.getElementById("panelVisualize"),
      robotReplay: document.getElementById("panelRobotReplay"),
    }};
    function activate(name) {{
      for (const button of buttons) button.classList.toggle("active", button.dataset.panel === name);
      for (const [key, panel] of Object.entries(panels)) panel.classList.toggle("active", key === name);
      history.replaceState(null, "", "#" + name);
    }}
    for (const button of buttons) button.addEventListener("click", () => activate(button.dataset.panel));
    const initial = location.hash.replace("#", "");
    if (panels[initial]) activate(initial);
    const autoButton = document.getElementById("autoCollect");
    const autoState = document.getElementById("autoCollectState");
    const autoBanner = document.getElementById("autoCollectBanner");
    const autoBadge = document.getElementById("autoCollectBadge");
    const autoDetail = document.getElementById("autoCollectDetail");
    const autoTopics = document.getElementById("autoCollectTopics");
    const stagedToggle = document.getElementById("stagedAutoCollect");
    let autoEnabled = false;
    let stagedEnabled = false;
    function phaseLabel(phase) {{
      return {{
        disabled: "未启用",
        idle: "监听中",
        starting: "启动本条录制中",
        recording: "录制中",
        saving: "保存中",
        error: "异常",
      }}[phase] || phase || "未知";
    }}
    async function refreshAutomation() {{
      try {{
        const response = await fetch("/automation/status", {{ cache: "no-store" }});
        const data = await response.json();
        autoEnabled = !!data.enabled;
        stagedEnabled = !!data.staged_enabled;
        autoButton.disabled = !data.available;
        stagedToggle.disabled = !data.available || ["starting", "recording", "saving"].includes(data.phase || "");
        stagedToggle.checked = stagedEnabled;
        autoButton.textContent = autoEnabled ? "关闭自动监听" : "启用自动监听";
        autoButton.classList.toggle("stop", autoEnabled);
        const phase = data.phase || (autoEnabled ? "idle" : "disabled");
        const message = data.message || (autoEnabled ? "自动监听已启用；未开始录制，等待 inference_record 与状态机 start 同时为 true" : "自动监听未启用");
        autoState.textContent = phaseLabel(phase);
        autoBadge.textContent = (stagedEnabled ? "分阶段：" : "自动监听：") + phaseLabel(phase);
        autoDetail.textContent = message;
        const topics = [];
        if (data.inference_record_topic) topics.push("推理录制 " + data.inference_record_topic);
        if (data.start_topic) topics.push("监听 " + data.start_topic);
        if (stagedEnabled && Array.isArray(data.stage_topics)) {{
          for (const item of data.stage_topics) {{
            if (item && item.primary) topics.push("阶段" + item.stage + " " + item.primary);
          }}
        }}
        if (data.end_topic) topics.push((stagedEnabled ? "最终结束 " : "结束 ") + data.end_topic);
        if (data.ready_topic) topics.push("反馈 " + data.ready_topic);
        autoTopics.textContent = topics.join("  |  ");
        autoBanner.classList.toggle("off", !autoEnabled);
        autoBanner.classList.toggle("error", phase === "error" || !!data.last_error);
      }} catch (error) {{
        autoButton.disabled = true;
        autoState.textContent = "自动监听状态不可用";
        autoBadge.textContent = "自动监听：异常";
        autoDetail.textContent = "无法读取自动监听状态";
        autoTopics.textContent = "";
        autoBanner.classList.add("error");
      }}
    }}
    async function toggleAutomation() {{
      autoButton.disabled = true;
      const endpoint = autoEnabled ? "/automation/stop" : "/automation/start";
      try {{
        await fetch(endpoint, {{ method: "POST", cache: "no-store" }});
      }} finally {{
        await refreshAutomation();
      }}
    }}
    async function toggleStagedAutomation() {{
      stagedToggle.disabled = true;
      try {{
        await fetch("/automation/staged", {{
          method: "POST",
          cache: "no-store",
          headers: {{ "Content-Type": "application/json" }},
          body: JSON.stringify({{ enabled: stagedToggle.checked }}),
        }});
      }} finally {{
        await refreshAutomation();
      }}
    }}
    autoButton.addEventListener("click", toggleAutomation);
    stagedToggle.addEventListener("change", toggleStagedAutomation);
    refreshAutomation();
    setInterval(refreshAutomation, 1500);
  </script>
</body>
</html>"""


class Handler(BaseHTTPRequestHandler):
    server_version = "UnifiedAlohaDataWeb/1.0"

    def send_json(self, status: int, payload: dict) -> None:
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    def do_GET(self) -> None:
        self.handle_request(send_body=True)

    def do_POST(self) -> None:
        self.handle_request(send_body=True)

    def do_HEAD(self) -> None:
        self.handle_request(send_body=False)

    def do_OPTIONS(self) -> None:
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, HEAD, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, Range")
        self.end_headers()

    def handle_request(self, send_body: bool = True) -> None:
        parsed = urlparse(self.path)
        if parsed.path in {"/", "/index.html"}:
            body = page().encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            if send_body and self.command != "HEAD":
                self.wfile.write(body)
            return
        if parsed.path == "/favicon.ico":
            self.send_response(204)
            self.end_headers()
            return
        if parsed.path == "/automation/status":
            self.send_json(200, read_automation_state())
            return
        if parsed.path == "/automation/start":
            if self.command != "POST":
                self.send_json(405, {"ok": False, "error": "POST required"})
                return
            self.send_json(202, {"ok": True, **set_automation_state(True)})
            return
        if parsed.path == "/automation/stop":
            if self.command != "POST":
                self.send_json(405, {"ok": False, "error": "POST required"})
                return
            self.send_json(202, {"ok": True, **set_automation_state(False)})
            return
        if parsed.path == "/automation/staged":
            if self.command != "POST":
                self.send_json(405, {"ok": False, "error": "POST required"})
                return
            try:
                payload = read_json_body(self)
            except json.JSONDecodeError as exc:
                self.send_json(400, {"ok": False, "error": str(exc)})
                return
            self.send_json(202, {"ok": True, **set_staged_automation_state(bool(payload.get("enabled", False)))})
            return

        backend, target = route_backend(parsed)
        if backend == "collection":
            if not collection_enabled:
                module_unavailable(self, "collection")
                return
            proxy(self, collection_url, with_query(target or "/", parsed.query), send_body=send_body)
            if self.command == "POST" and (target or "").rstrip("/") in {"/exit", "/quit"}:
                threading.Thread(target=self.server.shutdown, daemon=True).start()
            return
        if backend == "pipeline":
            if not pipeline_enabled:
                module_unavailable(self, "pipeline")
                return
            proxy(self, pipeline_url, with_query(target or "/", parsed.query), send_body=send_body)
            return
        if backend == "visualizer":
            if not visualizer_enabled:
                module_unavailable(self, "visualizer")
                return
            proxy(self, visualizer_url, with_query(target or "/", parsed.query), send_body=send_body)
            return

        payload = json.dumps({"ok": False, "error": "unknown route"}, ensure_ascii=False).encode("utf-8")
        self.send_response(404)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def log_message(self, fmt: str, *args) -> None:
        sys.stderr.write("[%s] %s\n" % (time.strftime("%F %T"), fmt % args))


class ReusableThreadingHTTPServer(ThreadingHTTPServer):
    allow_reuse_address = True


server = ReusableThreadingHTTPServer((host, port), Handler)
print(f"unified gateway listening on http://{host}:{port}/", flush=True)
try:
    server.serve_forever()
except KeyboardInterrupt:
    pass
finally:
    server.server_close()
PY
    GATEWAY_PID="$!"
    wait_for_port "${WEB_PORT}" "unified gateway" 10 "${WEB_HOST}"
}

start_state_machine_bridge() {
    is_truthy "${STATE_MACHINE_BRIDGE_ENABLE}" || return 0
    is_truthy "${COLLECTION_ENABLE}" || return 0
    [ -n "${COLLECTION_URL}" ] || die "状态机桥接需要采集模块 URL"

    local inference_record_topic="${INFERENCE_RECORD_TOPIC:-/inference_record}"
    local start_topic="${STATE_MACHINE_START_TOPIC:-/state_machine/start}"
    local end_topic="${STATE_MACHINE_END_TOPIC:-/state_machine/end}"
    local stage1_topic="${STATE_MACHINE_STAGE1_END_TOPIC:-/state_machine/approaching_container/end}"
    local stage2_topic="${STATE_MACHINE_STAGE2_END_TOPIC:-/state_machine/grasping/end}"
    local stage3_topic="${STATE_MACHINE_STAGE3_END_TOPIC:-/state_machine/approaching_shopping_cart/end}"
    local stage4_topic="${STATE_MACHINE_STAGE4_END_TOPIC:-/state_maching/put_back/end}"
    local stage4_aliases="${STATE_MACHINE_STAGE4_END_TOPIC_ALIASES:-/state_machine/put_back/end}"
    local ready_topic="${DATA_COLLECTION_START_TOPIC:-/data_collection/start}"
    local start_timeout="${STATE_MACHINE_START_TIMEOUT_SEC:-90}"
    local save_timeout="${DATA_COLLECTION_SAVE_TIMEOUT_SEC:-300}"
    local poll_interval="${STATE_MACHINE_POLL_INTERVAL_SEC:-0.2}"
    local publish_repeats="${DATA_COLLECTION_READY_PUBLISH_REPEATS:-8}"
    local initial_enabled="false"
    local initial_staged="false"
    local launcher=()
    if is_truthy "${STATE_MACHINE_AUTO_ACTIVE_DEFAULT}"; then
        initial_enabled="true"
    fi
    if is_truthy "${STATE_MACHINE_STAGED_DEFAULT}"; then
        initial_staged="true"
    fi

    python3 - \
        "${STATE_MACHINE_CONTROL_FILE}" \
        "${initial_enabled}" \
        "${initial_staged}" \
        "${inference_record_topic}" \
        "${start_topic}" \
        "${end_topic}" \
        "${ready_topic}" \
        "${COLLECTION_URL}" \
        "${stage1_topic}" \
        "${stage2_topic}" \
        "${stage3_topic}" \
        "${stage4_topic}" \
        "${stage4_aliases}" <<'PY'
import json
import os
import sys
import time

path = sys.argv[1]
enabled = sys.argv[2].lower() == "true"
staged_enabled = sys.argv[3].lower() == "true"
inference_record_topic = sys.argv[4]
start_topic = sys.argv[5]
end_topic = sys.argv[6]
ready_topic = sys.argv[7]
collection_url = sys.argv[8]
stage_topics = [
    {"stage": 1, "primary": sys.argv[9], "aliases": []},
    {"stage": 2, "primary": sys.argv[10], "aliases": []},
    {"stage": 3, "primary": sys.argv[11], "aliases": []},
    {
        "stage": 4,
        "primary": sys.argv[12],
        "aliases": [item for item in sys.argv[13].replace(",", " ").split() if item],
    },
]
os.makedirs(os.path.dirname(path), exist_ok=True)
tmp = f"{path}.tmp"
if enabled and staged_enabled:
    message = f"自动监听已启用；分阶段模式已选择，等待 {inference_record_topic}=true 且 {start_topic}=true 开启第一阶段。"
elif enabled:
    message = f"自动监听已启用；未开始录制，等待 {inference_record_topic}=true 且 {start_topic}=true 开启本条采集。"
else:
    message = "自动监听未启用；手动采集按钮可正常使用。"
with open(tmp, "w", encoding="utf-8") as handle:
    json.dump(
        {
            "enabled": enabled,
            "staged_enabled": staged_enabled,
            "phase": "idle" if enabled else "disabled",
            "message": message,
            "inference_record_topic": inference_record_topic,
            "inference_record_active": False,
            "state_machine_start_active": False,
            "start_topic": start_topic,
            "end_topic": end_topic,
            "stage_topics": stage_topics,
            "stage_count": 5,
            "active_stage": 0,
            "completed_stages": 0,
            "ready_topic": ready_topic,
            "collection_url": collection_url,
            "last_event": "",
            "last_error": "",
            "updated_at": time.strftime("%F %T"),
        },
        handle,
        ensure_ascii=False,
    )
os.replace(tmp, path)
PY

    log "启动推理状态机桥接: ${inference_record_topic} + ${start_topic} + ${end_topic} -> ${ready_topic}; staged_default=${initial_staged}"
    local cmd=(
        python3 -u -
        "${COLLECTION_URL}"
        "${start_topic}"
        "${end_topic}"
        "${inference_record_topic}"
        "${ready_topic}"
        "${start_timeout}"
        "${save_timeout}"
        "${poll_interval}"
        "${publish_repeats}"
        "${STATE_MACHINE_CONTROL_FILE}"
        "${stage1_topic}"
        "${stage2_topic}"
        "${stage3_topic}"
        "${stage4_topic}"
        "${stage4_aliases}"
    )
    if command -v setsid >/dev/null 2>&1; then
        launcher=(setsid)
    fi
    "${launcher[@]}" "${cmd[@]}" <<'PY' >"${STATE_MACHINE_BRIDGE_LOG}" 2>&1 &
from __future__ import annotations

import http.client
import json
import os
import queue
import sys
import time
from urllib.parse import urlparse

import rclpy
from rclpy.node import Node
from rclpy.executors import ExternalShutdownException
from rclpy.qos import DurabilityPolicy, QoSProfile, ReliabilityPolicy
from std_msgs.msg import Bool


collection_url = sys.argv[1].rstrip("/")
start_topic = sys.argv[2]
end_topic = sys.argv[3]
inference_record_topic = sys.argv[4]
ready_topic = sys.argv[5]
start_timeout = float(sys.argv[6])
save_timeout = float(sys.argv[7])
poll_interval = float(sys.argv[8])
publish_repeats = max(1, int(sys.argv[9]))
control_file = sys.argv[10]
raw_stage_topics = [
    (1, sys.argv[11], ""),
    (2, sys.argv[12], ""),
    (3, sys.argv[13], ""),
    (4, sys.argv[14], sys.argv[15]),
]


def split_topics(value: str) -> list[str]:
    return [item for item in value.replace(",", " ").split() if item]


stage_topic_groups: list[tuple[int, list[str]]] = []
stage_topics_for_status: list[dict] = []
for stage_no, primary, aliases in raw_stage_topics:
    topics: list[str] = []
    for topic in [primary, *split_topics(aliases)]:
        if topic and topic not in topics:
            topics.append(topic)
    stage_topic_groups.append((stage_no, topics))
    stage_topics_for_status.append(
        {
            "stage": stage_no,
            "primary": topics[0] if topics else "",
            "aliases": topics[1:],
        }
    )


def log(message: str) -> None:
    print(f"[{time.strftime('%F %T')}] {message}", flush=True)


def read_control() -> dict:
    try:
        with open(control_file, "r", encoding="utf-8") as handle:
            return json.load(handle)
    except (FileNotFoundError, json.JSONDecodeError):
        return {}


def write_control(**fields) -> None:
    data = read_control()
    data.update(fields)
    data.update(
        {
            "inference_record_topic": inference_record_topic,
            "start_topic": start_topic,
            "end_topic": end_topic,
            "stage_topics": stage_topics_for_status,
            "stage_count": 5,
            "ready_topic": ready_topic,
            "collection_url": collection_url,
            "updated_at": time.strftime("%F %T"),
        }
    )
    os.makedirs(os.path.dirname(control_file), exist_ok=True)
    tmp = f"{control_file}.tmp"
    with open(tmp, "w", encoding="utf-8") as handle:
        json.dump(data, handle, ensure_ascii=False)
    os.replace(tmp, control_file)


def automation_enabled() -> bool:
    return bool(read_control().get("enabled", False))


def automation_staged_enabled() -> bool:
    return bool(read_control().get("staged_enabled", False))


def set_status(
    phase: str,
    message: str,
    *,
    last_event: str = "",
    last_error: str = "",
    **fields,
) -> None:
    write_control(phase=phase, message=message, last_event=last_event, last_error=last_error, **fields)


class CollectionHttp:
    def __init__(self, base_url: str):
        parsed = urlparse(base_url)
        if parsed.scheme != "http" or not parsed.hostname or not parsed.port:
            raise ValueError(f"unsupported collection URL: {base_url}")
        self.host = parsed.hostname
        self.port = parsed.port

    def request(
        self,
        method: str,
        path: str,
        timeout: float = 10.0,
        *,
        body: bytes | None = None,
        headers: dict[str, str] | None = None,
    ) -> tuple[int, bytes]:
        conn = http.client.HTTPConnection(self.host, self.port, timeout=timeout)
        try:
            request_headers = {"Connection": "close"}
            if headers:
                request_headers.update(headers)
            if body is not None:
                request_headers["Content-Length"] = str(len(body))
            conn.request(method, path, body=body, headers=request_headers)
            resp = conn.getresponse()
            body = resp.read()
            if resp.status >= 400:
                raise RuntimeError(f"{method} {path} returned {resp.status}: {body[:300]!r}")
            return resp.status, body
        finally:
            conn.close()

    def status(self) -> dict:
        _, body = self.request("GET", "/status", timeout=5.0)
        return json.loads(body.decode("utf-8") or "{}")

    def post(self, path: str) -> None:
        self.request("POST", path, timeout=10.0)

    def post_json(self, path: str, payload: dict) -> None:
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.request(
            "POST",
            path,
            timeout=10.0,
            body=body,
            headers={"Content-Type": "application/json; charset=utf-8"},
        )


class StateMachineBridge(Node):
    def __init__(self):
        super().__init__("data_collection_state_machine_bridge")
        self.events: queue.SimpleQueue[str] = queue.SimpleQueue()
        self.inference_record_active = False
        self.state_machine_start_active = False
        ready_qos = QoSProfile(depth=1)
        ready_qos.reliability = ReliabilityPolicy.RELIABLE
        ready_qos.durability = DurabilityPolicy.TRANSIENT_LOCAL
        self.ready_pub = self.create_publisher(Bool, ready_topic, ready_qos)
        self.create_subscription(Bool, inference_record_topic, self._on_inference_record, 10)
        self.create_subscription(Bool, start_topic, self._on_start, 10)
        self.create_subscription(Bool, end_topic, self._on_end, 10)
        for stage_no, topics in stage_topic_groups:
            for topic in topics:
                self.create_subscription(
                    Bool,
                    topic,
                    lambda msg, stage_no=stage_no, topic=topic: self._on_stage(msg, stage_no, topic),
                    10,
                )

    def _on_inference_record(self, msg: Bool) -> None:
        self.inference_record_active = bool(msg.data)
        self.events.put("inference_record")

    def _on_start(self, msg: Bool) -> None:
        self.state_machine_start_active = bool(msg.data)
        self.events.put("start")

    def _on_end(self, msg: Bool) -> None:
        if msg.data:
            self.events.put("end")

    def _on_stage(self, msg: Bool, stage_no: int, topic: str) -> None:
        if msg.data:
            self.events.put(f"stage:{stage_no}:{topic}")

    def publish_ready(self, value: bool, repeats: int | None = None) -> None:
        msg = Bool()
        msg.data = bool(value)
        count = publish_repeats if repeats is None else max(1, int(repeats))
        for _ in range(count):
            self.ready_pub.publish(msg)
            try:
                rclpy.spin_once(self, timeout_sec=0.0)
            except ExternalShutdownException:
                return
            time.sleep(0.05)


def wait_for_status(http: CollectionHttp, predicate, timeout: float, label: str) -> dict:
    deadline = time.monotonic() + timeout
    last_status: dict = {}
    while rclpy.ok() and time.monotonic() < deadline:
        last_status = http.status()
        if predicate(last_status):
            return last_status
        time.sleep(max(0.05, poll_interval))
    raise TimeoutError(f"timed out waiting for {label}; last status={last_status}")


def status_summary(status: dict) -> str:
    return (
        f"state={status.get('state')!r}, "
        f"episode={status.get('episode')!r}, "
        f"capture_running={status.get('capture_running')!r}, "
        f"message={status.get('message')!r}"
    )


def is_recording_status(status: dict) -> bool:
    return bool(status.get("capture_running")) and str(status.get("state", "")).lower() == "recording"


def episode_changed(status: dict, previous_episode) -> bool:
    if previous_episode is None:
        return True
    return str(status.get("episode")) != str(previous_episode)


def collection_config_payload(status: dict, staged: bool) -> dict:
    return {
        "data_dir": status.get("data_dir", ""),
        "episode_index": str(status.get("episode", 0)),
        "with_base": bool(status.get("with_base", True)),
        "staged_capture": bool(staged),
        "auto_save_on_preset": False if staged else bool(status.get("auto_save_on_preset", False)),
        "run_convert": bool(status.get("run_convert", True)),
        "run_qc": bool(status.get("run_qc", True)),
        "run_lerobot": bool(status.get("run_lerobot", False)),
        "background_processing": bool(status.get("background_processing", True)),
        "preset_info_json": status.get("preset_info_json", ""),
        "target_bottle_a": status.get("target_bottle_a", ""),
        "target_bottle_b": status.get("target_bottle_b", ""),
        "lerobot_target_dir": status.get("lerobot_target_dir", ""),
        "lerobot_dataset_name": status.get("lerobot_dataset_name", ""),
    }


def configure_collection_for_mode(http: CollectionHttp, staged: bool) -> dict:
    status = http.status()
    if status.get("capture_running"):
        if bool(status.get("staged_capture")) != staged:
            raise RuntimeError(
                "collection is already recording with staged_capture="
                f"{status.get('staged_capture')}; cannot switch to {staged}"
            )
        return status
    http.post_json("/config", collection_config_payload(status, staged))
    return wait_for_status(
        http,
        lambda item: (
            bool(item.get("staged_capture")) == staged
            and (not staged or not bool(item.get("auto_save_on_preset")))
        ),
        8.0,
        f"collection config staged_capture={staged}",
    )


def expected_stage_topic(stage_no: int) -> str:
    for candidate_no, topics in stage_topic_groups:
        if candidate_no == stage_no and topics:
            return topics[0]
    return ""


def as_int(value, default: int = 0) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def main() -> int:
    http = CollectionHttp(collection_url)
    rclpy.init()
    node = StateMachineBridge()
    phase = "idle"
    enabled = automation_enabled()
    staged_enabled = automation_staged_enabled()
    episode_staged = False
    current_stage = 0
    inference_record_active = False
    state_machine_start_active = False

    def start_gate_open() -> bool:
        return inference_record_active and state_machine_start_active

    def enabled_idle_message() -> str:
        if automation_staged_enabled():
            return f"自动监听已启用；分阶段模式已选择，等待 {inference_record_topic}=true 且 {start_topic}=true 开启第一阶段。"
        return f"自动监听已启用；未开始录制，等待 {inference_record_topic}=true 且 {start_topic}=true 开启本条采集。"

    def gate_wait_message() -> str:
        if inference_record_active and not state_machine_start_active:
            return f"已收到 {inference_record_topic}=true，继续等待 {start_topic}=true。"
        if state_machine_start_active and not inference_record_active:
            return f"已收到 {start_topic}=true，继续等待 {inference_record_topic}=true。"
        return f"等待 {inference_record_topic}=true 且 {start_topic}=true 后启动本条采集。"

    def recording_wait_message(episode) -> str:
        if episode_staged:
            if current_stage <= 4:
                topic = expected_stage_topic(current_stage)
                return f"episode{episode} 正在分阶段采集：阶段 {current_stage}；等待 {topic}=true。"
            return f"episode{episode} 正在分阶段采集：阶段 5；等待 {end_topic}=true 保存。"
        return f"episode{episode} 已确认进入 recording；已发布 {ready_topic}=true，等待 {end_topic}=true。"

    def start_recording(reason: str, last_event: str, staged_for_episode: bool) -> None:
        nonlocal phase, episode_staged, current_stage
        phase = "starting"
        episode_staged = bool(staged_for_episode)
        current_stage = 1 if episode_staged else 0
        mode_text = "分阶段" if episode_staged else "不分阶段"
        set_status(
            "starting",
            f"{reason}，正在按{mode_text}模式启动本条录制；尚未发布 {ready_topic}=true。",
            last_event=last_event,
            inference_record_active=inference_record_active,
            state_machine_start_active=state_machine_start_active,
            active_stage=current_stage,
            completed_stages=0,
            episode_staged=episode_staged,
        )
        node.publish_ready(False, repeats=2)
        status = configure_collection_for_mode(http, episode_staged)
        log(f"start recording requested; mode={mode_text}; current " + status_summary(status))
        episode = status.get("episode")
        if is_recording_status(status):
            log("collection was already recording; " + status_summary(status))
            current_stage = as_int(status.get("current_stage"), current_stage) if episode_staged else 0
            set_status(
                "recording",
                recording_wait_message(episode),
                last_event=last_event,
                inference_record_active=inference_record_active,
                state_machine_start_active=state_machine_start_active,
                active_stage=current_stage,
                completed_stages=as_int(status.get("completed_stages"), 0),
                episode_staged=episode_staged,
            )
            node.publish_ready(True)
            phase = "recording"
            return
        set_status(
            "starting",
            f"{reason}，正在按{mode_text}模式启动 episode{episode} 录制；尚未发布 {ready_topic}=true。",
            last_event=last_event,
            inference_record_active=inference_record_active,
            state_machine_start_active=state_machine_start_active,
            active_stage=current_stage,
            completed_stages=0,
            episode_staged=episode_staged,
        )
        if not status.get("capture_running"):
            http.post("/start")
        status = wait_for_status(
            http,
            is_recording_status,
            start_timeout,
            "collection to enter recording state",
        )
        log("collection recording; " + status_summary(status))
        episode = status.get("episode")
        current_stage = as_int(status.get("current_stage"), current_stage) if episode_staged else 0
        set_status(
            "recording",
            recording_wait_message(episode),
            last_event=last_event,
            inference_record_active=inference_record_active,
            state_machine_start_active=state_machine_start_active,
            active_stage=current_stage,
            completed_stages=as_int(status.get("completed_stages"), 0),
            episode_staged=episode_staged,
        )
        node.publish_ready(True)
        phase = "recording"

    def mark_stage_boundary(stage_no: int, topic: str) -> dict:
        nonlocal current_stage
        status = http.status()
        if not is_recording_status(status):
            raise RuntimeError(f"stage {stage_no} received while collection is not recording; {status_summary(status)}")
        episode = status.get("episode")
        set_status(
            "recording",
            f"收到 {topic}=true，正在结束阶段 {stage_no} 并进入阶段 {stage_no + 1}。",
            last_event=f"stage{stage_no}",
            active_stage=stage_no,
            completed_stages=as_int(status.get("completed_stages"), 0),
            episode_staged=True,
        )
        http.post("/stage")
        status = wait_for_status(
            http,
            lambda item: is_recording_status(item) and as_int(item.get("completed_stages"), 0) >= stage_no,
            start_timeout,
            f"collection to mark stage {stage_no}",
        )
        current_stage = as_int(status.get("current_stage"), stage_no + 1)
        log(f"stage {stage_no} marked by {topic}; current " + status_summary(status))
        set_status(
            "recording",
            recording_wait_message(episode),
            last_event=f"stage{stage_no}",
            active_stage=current_stage,
            completed_stages=as_int(status.get("completed_stages"), stage_no),
            episode_staged=True,
        )
        node.publish_ready(True, repeats=2)
        return status

    def save_current_episode(last_event: str = "end") -> dict:
        nonlocal phase, episode_staged, current_stage
        phase = "saving"
        set_status(
            "saving",
            f"收到 {end_topic}=true，正在停止并保存本条数据；已发布 {ready_topic}=false。",
            last_event=last_event,
            inference_record_active=inference_record_active,
            state_machine_start_active=state_machine_start_active,
            active_stage=current_stage,
            episode_staged=episode_staged,
        )
        node.publish_ready(False, repeats=2)
        status = http.status()
        log("end received; current " + status_summary(status))
        episode = status.get("episode")
        set_status(
            "saving",
            f"正在停止并保存 episode{episode}。",
            last_event=last_event,
            inference_record_active=inference_record_active,
            state_machine_start_active=state_machine_start_active,
            active_stage=current_stage,
            completed_stages=as_int(status.get("completed_stages"), 0),
            episode_staged=episode_staged,
        )
        if not status.get("capture_running"):
            log("save requested but collection was not running; " + status_summary(status))
            return status
        http.post("/save")
        status = wait_for_status(
            http,
            lambda item: (not bool(item.get("capture_running"))) and episode_changed(item, episode),
            save_timeout,
            "collection to finish saving and advance episode",
        )
        log("collection saved; " + status_summary(status))
        episode_staged = False
        current_stage = 0
        return status

    try:
        log(
            "bridge ready: "
            f"inference_record_topic={inference_record_topic}, start_topic={start_topic}, "
            f"end_topic={end_topic}, ready_topic={ready_topic}, "
            f"stage_topics={stage_topics_for_status}, collection={collection_url}, "
            f"enabled={enabled}, staged_enabled={staged_enabled}"
        )
        set_status(
            "idle" if enabled else "disabled",
            (
                enabled_idle_message()
                if enabled
                else "自动监听未启用；手动采集按钮可正常使用。"
            ),
            staged_enabled=staged_enabled,
            inference_record_active=inference_record_active,
            state_machine_start_active=state_machine_start_active,
            active_stage=0,
            completed_stages=0,
            episode_staged=False,
        )
        node.publish_ready(False, repeats=2)
        while rclpy.ok():
            try:
                rclpy.spin_once(node, timeout_sec=0.1)
            except ExternalShutdownException:
                break
            current_enabled = automation_enabled()
            current_staged_enabled = automation_staged_enabled()
            if current_enabled != enabled:
                enabled = current_enabled
                log(f"automatic collection {'enabled' if enabled else 'disabled'}")
                if not enabled:
                    phase = "idle"
                    set_status(
                        "disabled",
                        "自动监听已关闭；手动采集按钮可正常使用。",
                        inference_record_active=inference_record_active,
                        state_machine_start_active=state_machine_start_active,
                        active_stage=0,
                        completed_stages=0,
                        episode_staged=False,
                    )
                    node.publish_ready(False)
                else:
                    set_status(
                        "idle",
                        enabled_idle_message(),
                        inference_record_active=inference_record_active,
                        state_machine_start_active=state_machine_start_active,
                        active_stage=0,
                        completed_stages=0,
                        episode_staged=False,
                    )
            if current_staged_enabled != staged_enabled:
                staged_enabled = current_staged_enabled
                log(f"staged automatic collection {'enabled' if staged_enabled else 'disabled'}")
                if phase == "idle":
                    set_status(
                        "idle" if enabled else "disabled",
                        enabled_idle_message() if enabled else "自动监听未启用；手动采集按钮可正常使用。",
                        staged_enabled=staged_enabled,
                        inference_record_active=inference_record_active,
                        state_machine_start_active=state_machine_start_active,
                        active_stage=0,
                        completed_stages=0,
                        episode_staged=False,
                    )

            try:
                event = node.events.get_nowait()
            except queue.Empty:
                continue

            if event in {"inference_record", "start"}:
                inference_record_active = node.inference_record_active
                state_machine_start_active = node.state_machine_start_active

            if not enabled:
                log(f"ignore {event} while automatic collection is disabled")
                set_status(
                    "disabled",
                    f"自动监听未启用，已忽略状态机事件 {event}。",
                    last_event=event,
                    inference_record_active=inference_record_active,
                    state_machine_start_active=state_machine_start_active,
                )
                node.publish_ready(False, repeats=1)
                continue

            if event in {"inference_record", "start"}:
                if phase in {"starting", "saving"}:
                    log(f"ignore {event} while phase={phase}")
                    continue
                if phase == "recording":
                    status = http.status()
                    if is_recording_status(status):
                        log(f"{event} received while already recording; confirmed by status, republish ready=true")
                        set_status(
                            "recording",
                            recording_wait_message(status.get("episode")),
                            last_event=event,
                            inference_record_active=inference_record_active,
                            state_machine_start_active=state_machine_start_active,
                            active_stage=current_stage,
                            completed_stages=as_int(status.get("completed_stages"), 0),
                            episode_staged=episode_staged,
                        )
                        node.publish_ready(True)
                        continue
                    log("local recording phase was stale; collection status is " + status_summary(status))
                    phase = "idle"

                if not start_gate_open():
                    log(
                        "start gate waiting: "
                        f"inference_record={inference_record_active}, start={state_machine_start_active}"
                    )
                    if phase == "idle":
                        set_status(
                            "idle",
                            gate_wait_message(),
                            last_event=event,
                            inference_record_active=inference_record_active,
                            state_machine_start_active=state_machine_start_active,
                            active_stage=0,
                            completed_stages=0,
                            episode_staged=False,
                        )
                    node.publish_ready(False, repeats=1)
                    continue

                try:
                    start_recording(
                        f"收到 {inference_record_topic}=true 且 {start_topic}=true，开启本条采集",
                        event,
                        automation_staged_enabled(),
                    )
                except Exception as exc:  # noqa: BLE001 - keep bridge alive after one failed cycle.
                    log(f"ERROR starting collection: {exc}")
                    set_status(
                        "error",
                        f"本条录制启动失败：{exc}",
                        last_event=event,
                        last_error=str(exc),
                        inference_record_active=inference_record_active,
                        state_machine_start_active=state_machine_start_active,
                        active_stage=current_stage,
                        episode_staged=episode_staged,
                    )
                    node.publish_ready(False)
                    phase = "idle"
                continue

            if event.startswith("stage:"):
                _, stage_text, topic = event.split(":", 2)
                stage_no = int(stage_text)
                if not episode_staged:
                    log(f"ignore staged event {event} while current episode is not staged")
                    set_status(
                        phase if phase != "idle" else "idle",
                        f"当前未按分阶段模式采集，已忽略 {topic}=true。",
                        last_event=f"stage{stage_no}",
                        active_stage=current_stage,
                        episode_staged=episode_staged,
                    )
                    continue
                if phase != "recording":
                    log(f"ignore staged event {event} while phase={phase}")
                    set_status(
                        phase,
                        f"当前状态为 {phase}，已忽略阶段事件 {topic}=true。",
                        last_event=f"stage{stage_no}",
                        active_stage=current_stage,
                        episode_staged=episode_staged,
                    )
                    continue
                if stage_no != current_stage:
                    log(f"ignore staged event {event}; expected stage {current_stage}")
                    set_status(
                        "recording",
                        f"收到阶段 {stage_no} 事件 {topic}=true，但当前等待阶段 {current_stage}，已忽略。",
                        last_event=f"stage{stage_no}",
                        active_stage=current_stage,
                        episode_staged=True,
                    )
                    continue
                if current_stage > 4:
                    log(f"ignore staged event {event}; waiting final end")
                    set_status(
                        "recording",
                        f"已进入阶段 5，等待 {end_topic}=true 保存，已忽略 {topic}=true。",
                        last_event=f"stage{stage_no}",
                        active_stage=current_stage,
                        episode_staged=True,
                    )
                    continue
                try:
                    mark_stage_boundary(stage_no, topic)
                except Exception as exc:  # noqa: BLE001
                    log(f"ERROR marking stage {stage_no}: {exc}")
                    set_status(
                        "error",
                        f"阶段 {stage_no} 切换失败：{exc}",
                        last_event=f"stage{stage_no}",
                        last_error=str(exc),
                        active_stage=current_stage,
                        episode_staged=True,
                    )
                    node.publish_ready(False)
                    phase = "recording"
                continue

            if event == "end":
                if phase in {"idle", "starting"}:
                    try:
                        status = http.status()
                    except Exception as exc:  # noqa: BLE001
                        log(f"end received while phase={phase}; status unavailable: {exc}")
                        set_status("error", f"收到结束信号但读取采集状态失败：{exc}", last_event="end", last_error=str(exc))
                        node.publish_ready(False)
                        phase = "idle"
                        continue
                    if not status.get("capture_running"):
                        log("end received but collection is not recording; " + status_summary(status))
                        set_status(
                            "idle",
                            f"收到 {end_topic}=true，但当前没有正在录制；等待 {inference_record_topic}=true 且 {start_topic}=true 开启本条采集。",
                            last_event="end",
                            inference_record_active=inference_record_active,
                            state_machine_start_active=state_machine_start_active,
                            active_stage=0,
                            completed_stages=0,
                            episode_staged=False,
                        )
                        node.publish_ready(False)
                        phase = "idle"
                        continue
                    phase = "recording"

                if phase == "saving":
                    log("ignore end while saving")
                    set_status("saving", "正在保存当前 episode，已忽略重复结束信号。", last_event="end")
                    continue

                try:
                    if episode_staged and current_stage < 5:
                        log(f"final end received before stage 5; current_stage={current_stage}")
                    saved_status = save_current_episode("end")
                    saved_message = saved_status.get("message")
                    next_episode = saved_status.get("episode")
                    set_status(
                        "idle",
                        f"保存完成，已切到 episode{next_episode}；等待 {inference_record_topic}=true 且 {start_topic}=true 开启下一条采集。",
                        last_event="end",
                        inference_record_active=inference_record_active,
                        state_machine_start_active=state_machine_start_active,
                        active_stage=0,
                        completed_stages=0,
                        episode_staged=False,
                    )
                    if saved_message:
                        log(f"save result message: {saved_message}")
                    node.publish_ready(False)
                    phase = "idle"
                except Exception as exc:  # noqa: BLE001
                    log(f"ERROR saving collection: {exc}")
                    set_status(
                        "error",
                        f"自动停止/保存失败：{exc}",
                        last_event="end",
                        last_error=str(exc),
                        active_stage=current_stage,
                        episode_staged=episode_staged,
                    )
                    node.publish_ready(False)
                    phase = "idle"
                continue
    finally:
        try:
            node.publish_ready(False, repeats=2)
        except Exception:
            pass
        node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
PY
    STATE_MACHINE_BRIDGE_PID="$!"
    sleep 1
    if ! kill -0 "${STATE_MACHINE_BRIDGE_PID}" >/dev/null 2>&1; then
        tail -120 "${STATE_MACHINE_BRIDGE_LOG}" >&2 || true
        die "状态机桥接启动失败"
    fi
}

cleanup() {
    set +e
    stop_child "${STATE_MACHINE_BRIDGE_PID:-}"
    stop_child "${GATEWAY_PID:-}"
    stop_child "${VISUALIZER_PID:-}"
    stop_child "${PIPELINE_PID:-}"
    stop_child "${COLLECTION_PID:-}"
    stop_port_listeners "${WEB_PORT:-}"
    stop_port_listeners "${VISUALIZER_WEB_PORT:-}"
    stop_port_listeners "${PIPELINE_WEB_PORT:-}"
    stop_port_listeners "${COLLECTION_WEB_PORT:-}"
}

handle_signal() {
    echo ""
    log "收到退出信号，正在停止统一数据网站。"
    cleanup
    exit 130
}

collection_acquire_session_lock
mkdir -p "${LOG_ROOT}" "${DATA_DIR}"
write_target_stage_preset
trap cleanup EXIT
trap handle_signal INT TERM

log "统一数据网站配置"
echo "  DATA_DIR=${DATA_DIR}"
echo "  START_INDEX=${START_INDEX}"
echo "  COLLECTION_ARM_MODE=${COLLECTION_ARM_MODE}"
echo "  TARGET_BOTTLE_A=${TARGET_BOTTLE_A}"
echo "  TARGET_BOTTLE_B=${TARGET_BOTTLE_B}"
echo "  STAGE_PRESET_INFO_JSON=${STAGE_PRESET_INFO_JSON}"
echo "  COLLECTION_SCENE_INVENTORY_JSON=${COLLECTION_SCENE_INVENTORY_JSON}"
echo "  WEB_HOST=${WEB_HOST}, WEB_PORT=${WEB_PORT}"
echo "  COLLECTION_ENABLE=${COLLECTION_ENABLE}, PIPELINE_ENABLE=${PIPELINE_ENABLE}, VISUALIZER_ENABLE=${VISUALIZER_ENABLE}"
echo "  COLLECTION_STAGED_CAPTURE_DEFAULT=${COLLECTION_STAGED_CAPTURE_DEFAULT}"
echo "  COLLECTION_AUTO_GRADE=${COLLECTION_AUTO_GRADE}"
echo "  STATE_MACHINE_BRIDGE_ENABLE=${STATE_MACHINE_BRIDGE_ENABLE:-1}"
echo "  STATE_MACHINE_AUTO_ACTIVE_DEFAULT=${STATE_MACHINE_AUTO_ACTIVE_DEFAULT:-1}"
echo "  STATE_MACHINE_STAGED_DEFAULT=${STATE_MACHINE_STAGED_DEFAULT:-0}"
echo "  INFERENCE_RECORD_TOPIC=${INFERENCE_RECORD_TOPIC:-/inference_record}"
echo "  STATE_MACHINE_START_TOPIC=${STATE_MACHINE_START_TOPIC:-/state_machine/start}"
echo "  STATE_MACHINE_END_TOPIC=${STATE_MACHINE_END_TOPIC:-/state_machine/end}"
echo "  STATE_MACHINE_STAGE1_END_TOPIC=${STATE_MACHINE_STAGE1_END_TOPIC:-/state_machine/approaching_container/end}"
echo "  STATE_MACHINE_STAGE2_END_TOPIC=${STATE_MACHINE_STAGE2_END_TOPIC:-/state_machine/grasping/end}"
echo "  STATE_MACHINE_STAGE3_END_TOPIC=${STATE_MACHINE_STAGE3_END_TOPIC:-/state_machine/approaching_shopping_cart/end}"
echo "  STATE_MACHINE_STAGE4_END_TOPIC=${STATE_MACHINE_STAGE4_END_TOPIC:-/state_maching/put_back/end}"
echo "  STATE_MACHINE_STAGE4_END_TOPIC_ALIASES=${STATE_MACHINE_STAGE4_END_TOPIC_ALIASES:-/state_machine/put_back/end}"
echo "  DATA_COLLECTION_START_TOPIC=${DATA_COLLECTION_START_TOPIC:-/data_collection/start}"
echo "  PIPELINE_ROOT=${PIPELINE_ROOT}"

start_collection
start_state_machine_bridge
start_pipeline
start_visualizer
start_gateway
print_web_urls

wait "${GATEWAY_PID}"
