scene_id: 2
scene_name: dual_piper_with_table_and_box
world_frame: world

robot:
  dual_arm_source: agilex_xpc_dual_piper_rviz
  base_distance: 0.6

table:
  enabled: true
  id: table
  frame_id: world
  type: box
  size_x: 1.2
  size_y: 0.4
  thickness: 0.05
  top_z: 0.0
  center_x: 0.3
  center_y: 0.0

obstacle:
  enabled: true
  id: scene_2_box
  frame_id: world
  type: box
  size_x: 0.06
  size_y: 0.06
  size_z: 0.30
  center_x: 0.26
  center_y: 0.17
  center_z: 0.15
